Homework 2
================
Tara Zhan

# Problem 1

``` r
# First, clean the data in 'pols-month.csv'.
pols_cleaned <- pols %>%
  # Separate the `mon` column into `year`, `month`, and `day`
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>%
  # Replace month number with month name
  mutate(month = month.abb[as.numeric(month)]) %>%
  # Create a `president` variable
  mutate(president = ifelse(!is.na(prez_dem), "dem", ifelse(!is.na(prez_gop), "gop", NA))) %>%
  # Remove `prez_dem`, `prez_gop`, `day` variables
  select(-day, -prez_dem, -prez_gop)
```

**pols_cleaned/(pols-month.csv)**: This dataset describes the voting
rate of presidents from 1947 to 2015. The cleaned version contains
variables like ‘year’, ‘month’, ‘political party of the president’ that
either Democratic (‘dem’) or republican (‘gop’).

``` r
# Second, clean the data in 'snp.csv'
snp_cleaned <- snp %>%
  # Separate the `date` column into `year`, `month`, and `day'
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) %>%
  # Replace month number with month name
  mutate(month = month.abb[as.numeric(month)]) %>%
  # Arrange the data by year and month
  arrange(year, month) %>%
  # Organize 'year' and 'month' are the leading columns
  select(year, month, everything(), -day)
```

**snp_cleaned/(snp.csv)**: This dataset describes the stock market
indexes over time. The cleaned version arranged data chronologically by
‘year’ and ‘month’, making the dataset easier to read. It also contains
‘close’ values.

``` r
# Third, tidy the 'unemployment.csv' then merged with the previous datasets
unemployment_long <- unemployment %>%
  #convert from wide to long format
  gather(key = "month", value = "unemployment_rate", -Year)
unemployment_long <- unemployment_long %>%
  rename(year = Year)
```

**unemployment_cleaned/(unemployment.csv)**: This dataset describes
unemployment rates in each months from 1948 to 2015. The tidying version
convert the dataset from wide to long format, making it easier to merge
with other datasets. It also contains ‘unemployment rate’ values.

``` r
# Merging 'snp' into 'pols', and merging 'unemployment' into the result.
combined_data <- pols_cleaned %>%
  # Merge 'snp' into 'pols'
  left_join(snp_cleaned, by = c("year", "month")) %>%
  # Merge 'unemployment'
  left_join(unemployment_long, by = c("year", "month"))
```

**combined_data:** This is a combination of three above cleaned version
datasets based on the ‘year’ and ‘month’. This combined dataset
describes an outlook of political, economic, and unemployment rates from
year 1948 to year 2015. This combined_data has 11 columns, 822 rows, and
spans from the year 1947 to 2015. Key variables in this dataset include:
year, month, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem,
president, close, unemployment_rate.

# Problem 2

``` r
# clean Mr. Trash Wheel sheet, and add a new variables
mr_trash_wheel <- 
  read_excel("trash_wheel_collection.xlsx", 1, range="A2:N549") |>
  janitor::clean_names() |>
  filter(homes_powered!=0.00000) |>
# based on calculation.
  mutate(homes_powered = weight_tons * (500/30))
view(mr_trash_wheel)
```

``` r
#clean Professor Trash Wheel sheet 
prof_trash_wheel <- 
  read_excel("trash_wheel_collection.xlsx", 2, range="A2:M96") |>
  janitor::clean_names() |>
  drop_na() |>
# based on calculation.
  mutate(homes_powered = weight_tons * (500/30))
view(prof_trash_wheel)
```

``` r
#clean Gwynnda Trash Wheel sheet 
gwyn_trash_wheel <- 
  read_excel("trash_wheel_collection.xlsx", 4, range="A2:K108") |>
  janitor::clean_names() |>
  drop_na() |>
# based on calculation.
  mutate(homes_powered = weight_tons * (500/30))
view(gwyn_trash_wheel)
```

``` r
# Add wheel_name
mr_trash_wheel <- mr_trash_wheel %>%
  mutate(wheel_name = "Mr. Trash Wheel")
prof_trash_wheel <- prof_trash_wheel %>%
  mutate(wheel_name = "Professor Trash Wheel")
gwyn_trash_wheel <- gwyn_trash_wheel %>%
  mutate(wheel_name = "Gwynnda Trash Wheel")
# Convert year to numeric
mr_trash_wheel$year <- as.numeric(mr_trash_wheel$year)
prof_trash_wheel$year <- as.numeric(prof_trash_wheel$year)
gwyn_trash_wheel$year <- as.numeric(gwyn_trash_wheel$year)

#combine all datasets
combined_trash_wheel <- bind_rows(mr_trash_wheel, prof_trash_wheel, gwyn_trash_wheel)
# View the combined dataset
view(combined_trash_wheel)
```

The “combined_trash_wheel” dataset is a combination of data derived from
Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda Trash Wheel. This
combination includes a total of 519 observations, and calculate the
number of homes powered. It is computed using the formula provided,
where each ton of trash is equated to 500 kilowatts of electricity.  
For available data, the total weight of trash collected by Professor
Trash Wheel is 162.54 tons. The total number of cigarette butts
collected by Gwynnda in July of 2021 is 1.63^{4} cigarette butts.

# Problem 3

``` r
# Read CSV files:
baseline <- 
  read.csv("data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  rename("study_id" = "id")
# Convert sex and APOE4 status to factor 
  baseline %>%
    mutate(
      sex = recode(sex, "1" = "male", "0" = "female"),
      apoe4 = recode(apoe4, "1" = "carrier", "0" = "non-carrier")
      )
```

    ##     study_id current_age    sex education       apoe4 age_at_onset
    ## 1          1        63.1 female        16     carrier            .
    ## 2          2        65.6 female        20     carrier            .
    ## 3          3        62.5   male        16     carrier         66.8
    ## 4          4        69.8 female        16 non-carrier            .
    ## 5          5        66.0   male        16 non-carrier         68.7
    ## 6          6        62.5   male        16 non-carrier            .
    ## 7          7        66.5   male        18 non-carrier           74
    ## 8          8        67.2 female        18 non-carrier            .
    ## 9          9        66.7 female        16 non-carrier            .
    ## 10        10        64.1 female        18 non-carrier            .
    ## 11        11        69.5 female        16 non-carrier            .
    ## 12        12        66.2 female        18 non-carrier            .
    ## 13        13        63.1   male        12     carrier           69
    ## 14        14        58.4 female        20 non-carrier         66.2
    ## 15        15        68.4   male        20 non-carrier            .
    ## 16        16        64.9 female        16 non-carrier            .
    ## 17        17        65.0 female        18 non-carrier            .
    ## 18        18        67.8   male        16 non-carrier         69.8
    ## 19        19        67.5   male        16     carrier            .
    ## 20        20        66.8   male        16 non-carrier            .
    ## 21        21        67.8   male        16 non-carrier            .
    ## 22        22        67.3 female        20     carrier         74.6
    ## 23        23        65.2   male        18 non-carrier            .
    ## 24        24        59.0 female        12 non-carrier            .
    ## 25        25        66.9   male        16 non-carrier            .
    ## 26        26        64.8 female        20     carrier         71.1
    ## 27        27        64.5 female        16 non-carrier            .
    ## 28        28        60.6   male        20 non-carrier            .
    ## 29        29        63.6   male        16 non-carrier            .
    ## 30        30        66.3 female        12 non-carrier         73.1
    ## 31        31        69.1 female        12 non-carrier            .
    ## 32        32        64.7   male        16 non-carrier            .
    ## 33        33        66.2   male        18 non-carrier            .
    ## 34        34        64.8 female        16     carrier            .
    ## 35        35        60.9 female        12 non-carrier            .
    ## 36        36        63.8   male        16 non-carrier            .
    ## 37        37        63.8   male        16 non-carrier            .
    ## 38        38        64.8 female        18 non-carrier            .
    ## 39        39        68.3 female        16     carrier         70.2
    ## 40        40        67.3   male        16 non-carrier            .
    ## 41        41        64.5   male        16 non-carrier            .
    ## 42        42        64.2   male        16 non-carrier            .
    ## 43        43        67.1 female        16     carrier         71.6
    ## 44        44        66.7   male        20 non-carrier            .
    ## 45        45        62.9   male        20     carrier         65.2
    ## 46        46        62.9   male        16 non-carrier            .
    ## 47        47        66.1 female        12     carrier            .
    ## 48        48        67.3   male        16 non-carrier            .
    ## 49        49        64.7   male        16 non-carrier         68.4
    ## 50        50        67.6 female        18     carrier            .
    ## 51        51        66.2   male        16 non-carrier            .
    ## 52        52        63.2 female        16     carrier            .
    ## 53        53        66.0   male        20 non-carrier            .
    ## 54        54        61.6 female        16 non-carrier            .
    ## 55        55        69.3 female        16     carrier         73.6
    ## 56        56        70.9   male        20 non-carrier            .
    ## 57        57        63.9 female        16 non-carrier            .
    ## 58        58        61.9   male        12 non-carrier            .
    ## 59        59        66.7 female        20     carrier         74.4
    ## 60        60        64.6   male        18 non-carrier            .
    ## 61        61        72.2   male        16 non-carrier            .
    ## 62        62        64.9 female        18 non-carrier            .
    ## 63        63        67.1 female        20 non-carrier            .
    ## 64        64        65.1   male        16     carrier            .
    ## 65        65        62.8 female        16 non-carrier         66.5
    ## 66        66        65.6 female        20 non-carrier            .
    ## 67        67        59.6   male        18 non-carrier         64.2
    ## 68        68        69.4   male        20 non-carrier            .
    ## 69        69        65.5 female        20     carrier         72.5
    ## 70        70        71.5   male        16 non-carrier            .
    ## 71        71        66.4   male        16 non-carrier            .
    ## 72        72        62.9   male        16     carrier         62.5
    ## 73        73        66.8 female        18 non-carrier            .
    ## 74        74        62.2   male        20     carrier            .
    ## 75        75        61.2 female        16     carrier         65.4
    ## 76        76        65.9   male        12 non-carrier           68
    ## 77        77        63.7 female        18     carrier         66.4
    ## 78        78        65.0   male        16 non-carrier           68
    ## 79        79        65.2   male        16 non-carrier            .
    ## 80        80        63.2   male        20 non-carrier            .
    ## 81        81        63.3   male        16 non-carrier            .
    ## 82        82        64.6   male        12 non-carrier            .
    ## 83        83        68.5 female        12 non-carrier            .
    ## 84        84        60.4   male        20 non-carrier            .
    ## 85        85        66.8 female        16 non-carrier            .
    ## 86        86        66.0 female        18     carrier         71.7
    ## 87        87        68.2   male        18 non-carrier           76
    ## 88        88        64.1   male        16 non-carrier            .
    ## 89        89        66.1 female        16     carrier         66.2
    ## 90        90        65.8   male        16 non-carrier            .
    ## 91        91        63.4   male        16     carrier            .
    ## 92        92        68.6 female        20 non-carrier            .
    ## 93        93        68.5   male        16     carrier            .
    ## 94        94        67.1   male        16 non-carrier            .
    ## 95        95        69.8 female        16 non-carrier            .
    ## 96        96        66.7 female        16 non-carrier            .
    ## 97        97        61.2   male        16 non-carrier            .
    ## 98        98        63.3 female        16     carrier            .
    ## 99        99        61.3 female        20 non-carrier            .
    ## 100      100        63.6 female        16 non-carrier            .
    ## 101      101        63.1 female        16 non-carrier            .
    ## 102      102        65.1   male        16 non-carrier            .
    ## 103      103        62.3   male        16 non-carrier            .
    ## 104      104        65.5   male        12 non-carrier            .
    ## 105      105        63.0   male        20 non-carrier            .
    ## 106      106        70.3 female        16     carrier         74.8
    ## 107      107        67.2   male        16     carrier            .
    ## 108      108        67.7   male        16 non-carrier            .
    ## 109      109        66.2 female        16     carrier         68.4
    ## 110      110        70.0   male        16 non-carrier            .
    ## 111      111        63.1   male        16 non-carrier            .
    ## 112      112        63.6 female        18 non-carrier            .
    ## 113      113        69.3   male        16     carrier            .
    ## 114      114        63.0 female        18     carrier            .
    ## 115      115        64.4 female        20 non-carrier            .
    ## 116      116        63.8   male        20 non-carrier            .
    ## 117      117        64.0   male        18     carrier            .
    ## 118      118        64.2 female        16     carrier            .
    ## 119      119        66.5   male        16 non-carrier            .
    ## 120      120        64.5 female        20     carrier         72.2
    ## 121      121        63.5   male        18 non-carrier            .
    ## 122      122        69.0 female        16 non-carrier            .
    ## 123      123        64.4   male        18     carrier         67.4
    ## 124      124        64.5 female        16 non-carrier            .
    ## 125      125        64.7 female        18     carrier            .
    ## 126      126        67.1 female        20 non-carrier            .
    ## 127      127        64.8   male        16 non-carrier            .
    ## 128      128        64.9   male        12 non-carrier            .
    ## 129      129        63.0   male        16 non-carrier            .
    ## 130      130        64.0   male        18     carrier            .
    ## 131      131        65.2 female        12 non-carrier            .
    ## 132      132        63.2   male        16     carrier           66
    ## 133      133        66.6   male        18 non-carrier            .
    ## 134      134        60.4   male        16     carrier            .
    ## 135      135        65.9   male        16 non-carrier            .
    ## 136      136        60.4   male        16 non-carrier            .
    ## 137      137        64.1   male        16 non-carrier            .
    ## 138      138        63.4 female        16     carrier            .
    ## 139      139        63.0 female        18 non-carrier            .
    ## 140      140        64.8   male        16 non-carrier            .
    ## 141      141        59.3   male        16     carrier            .
    ## 142      142        68.5   male        18 non-carrier            .
    ## 143      143        60.0 female        20 non-carrier            .
    ## 144      144        63.6   male        16 non-carrier            .
    ## 145      145        61.7 female        18 non-carrier            .
    ## 146      146        62.7 female        16 non-carrier         66.7
    ## 147      147        71.3   male        16 non-carrier            .
    ## 148      148        65.1   male        16 non-carrier            .
    ## 149      149        61.1 female        16     carrier         68.9
    ## 150      150        60.1   male        12 non-carrier            .
    ## 151      151        66.4 female        16 non-carrier            .
    ## 152      152        64.9   male        16 non-carrier            .
    ## 153      153        64.0 female        16 non-carrier            .
    ## 154      154        62.2 female        16 non-carrier            .
    ## 155      155        60.5 female        12 non-carrier            .
    ## 156      156        61.8   male        18 non-carrier            .
    ## 157      157        68.0   male        16     carrier            .
    ## 158      158        63.1   male        18 non-carrier            .
    ## 159      159        60.8   male        16 non-carrier            .
    ## 160      160        70.6   male        16 non-carrier            .
    ## 161      161        66.3   male        16     carrier            .
    ## 162      162        64.3   male        16     carrier            .
    ## 163      163        68.2 female        12 non-carrier            .
    ## 164      164        67.7   male        16 non-carrier            .
    ## 165      165        63.1 female        20 non-carrier            .
    ## 166      166        71.6   male        12     carrier         74.2
    ## 167      167        64.2 female        16 non-carrier            .
    ## 168      168        60.7   male        16 non-carrier            .
    ## 169      169        64.6 female        16 non-carrier            .
    ## 170      170        65.6   male        16 non-carrier         70.7
    ## 171      171        71.9 female        20 non-carrier            .
    ## 172      172        65.3 female        20 non-carrier            .
    ## 173      173        66.4   male        12     carrier            .
    ## 174      174        64.8   male        16 non-carrier            .
    ## 175      175        64.0 female        18 non-carrier            .
    ## 176      176        64.9   male        18 non-carrier            .
    ## 177      177        67.4 female        16     carrier         74.4
    ## 178      178        71.2 female        20 non-carrier            .
    ## 179      179        68.1   male        16 non-carrier            .
    ## 180      180        68.6   male        16 non-carrier            .
    ## 181      181        61.3   male        12     carrier            .
    ## 182      182        68.0   male        18     carrier            .
    ## 183      183        65.7   male        16     carrier            .
    ## 184      184        60.6   male        20 non-carrier            .
    ## 185      185        66.6 female        12 non-carrier            .
    ## 186      186        64.5   male        20     carrier         69.5
    ## 187      187        69.4   male        16 non-carrier            .
    ## 188      188        62.7 female        12 non-carrier            .
    ## 189      189        63.7   male        16 non-carrier            .
    ## 190      190        62.2   male        12 non-carrier            .
    ## 191      191        64.5 female        16 non-carrier            .
    ## 192      192        66.2 female        16     carrier            .
    ## 193      193        62.8   male        20     carrier            .
    ## 194      194        67.5 female        16     carrier            .
    ## 195      195        61.4   male        18     carrier            .
    ## 196      196        61.9 female        16 non-carrier            .
    ## 197      197        69.3 female        16 non-carrier            .
    ## 198      198        62.0 female        18 non-carrier            .
    ## 199      199        66.2   male        18 non-carrier            .
    ## 200      200        63.9   male        16 non-carrier            .
    ## 201      201        66.2   male        18 non-carrier            .
    ## 202      202        70.1 female        18     carrier         75.2
    ## 203      203        69.8 female        18 non-carrier            .
    ## 204      204        64.0 female        16 non-carrier            .
    ## 205      205        58.1 female        16     carrier            .
    ## 206      206        72.5 female        16 non-carrier            .
    ## 207      207        67.0 female        16 non-carrier            .
    ## 208      208        66.6 female        18 non-carrier            .
    ## 209      209        65.0   male        16 non-carrier            .
    ## 210      210        66.5 female        16 non-carrier            .
    ## 211      211        64.5   male        16 non-carrier            .
    ## 212      212        66.3 female        16     carrier            .
    ## 213      213        63.8   male        16 non-carrier            .
    ## 214      214        60.9   male        16 non-carrier            .
    ## 215      215        68.0   male        16 non-carrier            .
    ## 216      216        69.6 female        12 non-carrier            .
    ## 217      217        64.1 female        16 non-carrier            .
    ## 218      218        61.2   male        16 non-carrier         65.9
    ## 219      219        66.9 female        16     carrier            .
    ## 220      220        64.9   male        16 non-carrier            .
    ## 221      221        59.8 female        18 non-carrier            .
    ## 222      222        65.0   male        16 non-carrier            .
    ## 223      223        63.1 female        20     carrier            .
    ## 224      224        64.0 female        12 non-carrier            .
    ## 225      225        61.5   male        16 non-carrier            .
    ## 226      226        70.4   male        16 non-carrier         75.4
    ## 227      227        64.0   male        16     carrier            .
    ## 228      228        60.2   male        12 non-carrier            .
    ## 229      229        65.6 female        18 non-carrier         70.9
    ## 230      230        65.8 female        20     carrier         70.8
    ## 231      231        62.0   male        12     carrier            .
    ## 232      232        56.3   male        16 non-carrier            .
    ## 233      233        63.1   male        16 non-carrier            .
    ## 234      234        66.7   male        18 non-carrier         66.7
    ## 235      235        64.8   male        16 non-carrier            .
    ## 236      236        64.7 female        18 non-carrier            .
    ## 237      237        66.7   male        16 non-carrier            .
    ## 238      238        61.4   male        16 non-carrier            .
    ## 239      239        68.3   male        16 non-carrier            .
    ## 240      240        65.0 female        16     carrier            .
    ## 241      241        67.1   male        12 non-carrier            .
    ## 242      242        68.1   male        12 non-carrier         75.6
    ## 243      243        65.7   male        18 non-carrier            .
    ## 244      244        62.4   male        16 non-carrier            .
    ## 245      245        68.5 female        16 non-carrier            .
    ## 246      246        59.0 female        16 non-carrier            .
    ## 247      247        63.4 female        16 non-carrier            .
    ## 248      248        64.2 female        20 non-carrier            .
    ## 249      249        64.5 female        16     carrier         68.4
    ## 250      250        68.1   male        16     carrier         74.5
    ## 251      251        65.4   male        16 non-carrier            .
    ## 252      252        66.2   male        16     carrier         69.6
    ## 253      253        64.8 female        16 non-carrier            .
    ## 254      254        64.3 female        16 non-carrier            .
    ## 255      255        67.1   male        20 non-carrier            .
    ## 256      256        68.4   male        16 non-carrier            .
    ## 257      257        57.8   male        18 non-carrier            .
    ## 258      258        66.7   male        16 non-carrier            .
    ## 259      259        66.1 female        16 non-carrier            .
    ## 260      260        63.7   male        18     carrier            .
    ## 261      261        67.9   male        16     carrier            .
    ## 262      262        63.8 female        16 non-carrier            .
    ## 263      263        64.1   male        18 non-carrier            .
    ## 264      264        67.6 female        16 non-carrier            .
    ## 265      265        70.2   male        16 non-carrier            .
    ## 266      266        65.8   male        16 non-carrier            .
    ## 267      267        63.7   male        16 non-carrier            .
    ## 268      268        61.4 female        18     carrier         67.5
    ## 269      269        64.0   male        20 non-carrier            .
    ## 270      270        62.2   male        16     carrier            .
    ## 271      271        64.2   male        12     carrier            .
    ## 272      272        66.2   male        16     carrier            .
    ## 273      273        62.4 female        16 non-carrier            .
    ## 274      274        72.9 female        16 non-carrier            .
    ## 275      275        65.5 female        12 non-carrier            .
    ## 276      276        68.4 female        16     carrier            .
    ## 277      277        58.1   male        16     carrier         61.6
    ## 278      278        67.2 female        16 non-carrier            .
    ## 279      279        61.1 female        18 non-carrier            .
    ## 280      280        67.8 female        16     carrier         71.8
    ## 281      281        66.2   male        16     carrier            .
    ## 282      282        63.8 female        16     carrier            .
    ## 283      283        69.0   male        16 non-carrier         68.3
    ## 284      284        62.9 female        16 non-carrier            .
    ## 285      285        63.3 female        12 non-carrier            .
    ## 286      286        62.0   male        16     carrier         67.4
    ## 287      287        63.0   male        16     carrier           68
    ## 288      288        67.8 female        16 non-carrier            .
    ## 289      289        66.3   male        18     carrier         74.1
    ## 290      290        68.0   male        12 non-carrier            .
    ## 291      291        63.8   male        16 non-carrier            .
    ## 292      292        66.1 female        18 non-carrier         70.2
    ## 293      293        65.7 female        16 non-carrier            .
    ## 294      294        60.7   male        18 non-carrier            .
    ## 295      295        70.3   male        20 non-carrier            .
    ## 296      296        65.4 female        16 non-carrier            .
    ## 297      297        67.3   male        16     carrier         73.9
    ## 298      298        67.9   male        16 non-carrier            .
    ## 299      299        64.8   male        16 non-carrier            .
    ## 300      300        64.1   male        16     carrier            .
    ## 301      301        67.7 female        16 non-carrier         73.4
    ## 302      302        61.9   male        16     carrier            .
    ## 303      303        70.9   male        16 non-carrier            .
    ## 304      304        63.8 female        16 non-carrier            .
    ## 305      305        70.0 female        18     carrier         77.2
    ## 306      306        69.5 female        16 non-carrier         72.6
    ## 307      307        65.2   male        16 non-carrier            .
    ## 308      308        66.7 female        12     carrier            .
    ## 309      309        61.9 female        18 non-carrier            .
    ## 310      310        66.0   male        16     carrier            .
    ## 311      311        68.1   male        16 non-carrier            .
    ## 312      312        65.3   male        16 non-carrier            .
    ## 313      313        63.6   male        18 non-carrier            .
    ## 314      314        63.0 female        16 non-carrier         68.7
    ## 315      315        64.9 female        16 non-carrier            .
    ## 316      316        68.2 female        16 non-carrier            .
    ## 317      317        63.5   male        18 non-carrier            .
    ## 318      318        64.6   male        12 non-carrier            .
    ## 319      319        61.1 female        16 non-carrier            .
    ## 320      320        66.5   male        18 non-carrier            .
    ## 321      321        68.9 female        16 non-carrier            .
    ## 322      322        69.5   male        20     carrier            .
    ## 323      323        67.4 female        16     carrier         73.9
    ## 324      324        59.4   male        16 non-carrier            .
    ## 325      325        66.4   male        16 non-carrier            .
    ## 326      326        66.4 female        16 non-carrier            .
    ## 327      327        63.9   male        16 non-carrier            .
    ## 328      328        65.5   male        16 non-carrier           71
    ## 329      329        62.4   male        12 non-carrier            .
    ## 330      330        67.0 female        18     carrier            .
    ## 331      331        64.0   male        16 non-carrier            .
    ## 332      332        60.3 female        12 non-carrier            .
    ## 333      333        63.9   male        16     carrier            .
    ## 334      334        69.1   male        20 non-carrier            .
    ## 335      335        64.0 female        18 non-carrier            .
    ## 336      336        67.2 female        16     carrier         73.7
    ## 337      337        67.8 female        16 non-carrier           75
    ## 338      338        65.0 female        16 non-carrier         70.8
    ## 339      339        63.9 female        12 non-carrier            .
    ## 340      340        63.4   male        16 non-carrier            .
    ## 341      341        67.2   male        18 non-carrier            .
    ## 342      342        61.8   male        20 non-carrier            .
    ## 343      343        65.7 female        12 non-carrier            .
    ## 344      344        64.1   male        12     carrier            .
    ## 345      345        58.2   male        18 non-carrier            .
    ## 346      346        60.8   male        16     carrier            .
    ## 347      347        67.7   male        16     carrier         68.9
    ## 348      348        64.4   male        16     carrier         70.4
    ## 349      349        67.4 female        18     carrier           70
    ## 350      350        70.7 female        16     carrier         75.2
    ## 351      351        69.4   male        16     carrier         76.6
    ## 352      352        67.0   male        16     carrier         69.3
    ## 353      353        66.1   male        16 non-carrier            .
    ## 354      354        64.4   male        20     carrier            .
    ## 355      355        69.7   male        16     carrier         75.3
    ## 356      356        66.8 female        20 non-carrier            .
    ## 357      357        61.5 female        20 non-carrier            .
    ## 358      358        64.5   male        12     carrier            .
    ## 359      359        59.2   male        18 non-carrier            .
    ## 360      360        64.4 female        18 non-carrier            .
    ## 361      361        57.2 female        18     carrier            .
    ## 362      362        68.9 female        16 non-carrier            .
    ## 363      363        63.1   male        20 non-carrier            .
    ## 364      364        63.7   male        18 non-carrier            .
    ## 365      365        64.5 female        16 non-carrier         67.7
    ## 366      366        66.8   male        16     carrier         72.8
    ## 367      367        67.0 female        16 non-carrier            .
    ## 368      368        66.7   male        16 non-carrier            .
    ## 369      369        63.3   male        18     carrier         68.6
    ## 370      370        60.9 female        16     carrier            .
    ## 371      371        63.8   male        12     carrier            .
    ## 372      372        65.8   male        16 non-carrier            .
    ## 373      373        62.5   male        16 non-carrier           66
    ## 374      374        64.8   male        18 non-carrier            .
    ## 375      375        61.5 female        16 non-carrier            .
    ## 376      376        65.0 female        16 non-carrier            .
    ## 377      377        65.4 female        16     carrier         68.2
    ## 378      378        64.6 female        16     carrier            .
    ## 379      379        64.5   male        16 non-carrier         70.9
    ## 380      380        70.3 female        16 non-carrier         70.2
    ## 381      381        67.3 female        16     carrier            .
    ## 382      382        68.3 female        20 non-carrier            .
    ## 383      383        62.2   male        18 non-carrier            .
    ## 384      384        65.5   male        16 non-carrier            .
    ## 385      385        68.5   male        20 non-carrier            .
    ## 386      386        64.8   male        16     carrier            .
    ## 387      387        58.6   male        16     carrier            .
    ## 388      388        66.0 female        16 non-carrier            .
    ## 389      389        59.3 female        16 non-carrier            .
    ## 390      390        62.6 female        16 non-carrier            .
    ## 391      391        69.0 female        18 non-carrier            .
    ## 392      392        66.8   male        16 non-carrier            .
    ## 393      393        68.3   male        12 non-carrier            .
    ## 394      394        65.9 female        16 non-carrier            .
    ## 395      395        64.7 female        12 non-carrier            .
    ## 396      396        62.2   male        18 non-carrier            .
    ## 397      397        69.8 female        16 non-carrier            .
    ## 398      398        65.1 female        16 non-carrier           73
    ## 399      399        62.9   male        18 non-carrier            .
    ## 400      400        67.6 female        16 non-carrier         71.9
    ## 401      401        68.2   male        20 non-carrier            .
    ## 402      402        70.7 female        16 non-carrier            .
    ## 403      403        63.2 female        16     carrier            .
    ## 404      404        63.8   male        20     carrier            .
    ## 405      405        63.8   male        18 non-carrier            .
    ## 406      406        63.9 female        16 non-carrier            .
    ## 407      407        63.9   male        16 non-carrier            .
    ## 408      408        64.1   male        20     carrier         70.2
    ## 409      409        69.3   male        16     carrier         75.2
    ## 410      410        62.9   male        16 non-carrier            .
    ## 411      411        63.8   male        16     carrier            .
    ## 412      412        67.0   male        16     carrier            .
    ## 413      413        68.4   male        20 non-carrier            .
    ## 414      414        62.7 female        16 non-carrier            .
    ## 415      415        63.5   male        18 non-carrier            .
    ## 416      416        66.6 female        16 non-carrier         68.9
    ## 417      417        68.1 female        16     carrier         72.5
    ## 418      418        64.2   male        12     carrier            .
    ## 419      419        60.7 female        16     carrier         63.8
    ## 420      420        70.1   male        16 non-carrier            .
    ## 421      421        69.3 female        16 non-carrier            .
    ## 422      422        62.9 female        12     carrier            .
    ## 423      423        64.8 female        16     carrier         70.3
    ## 424      424        59.7   male        18     carrier         62.9
    ## 425      425        66.7   male        16 non-carrier            .
    ## 426      426        69.8   male        16 non-carrier         76.8
    ## 427      427        60.1   male        12 non-carrier            .
    ## 428      428        62.7   male        18 non-carrier            .
    ## 429      429        63.1   male        16     carrier            .
    ## 430      430        63.0 female        20 non-carrier            .
    ## 431      431        58.9   male        16     carrier         61.2
    ## 432      432        66.5 female        16 non-carrier            .
    ## 433      433        60.4   male        12     carrier            .
    ## 434      434        64.9   male        16 non-carrier            .
    ## 435      435        66.8 female        16 non-carrier            .
    ## 436      436        64.4   male        12     carrier            .
    ## 437      437        67.7 female        18     carrier            .
    ## 438      438        64.9 female        16 non-carrier            .
    ## 439      439        63.1 female        16 non-carrier            .
    ## 440      440        66.9   male        16     carrier         72.3
    ## 441      441        63.7 female        18 non-carrier            .
    ## 442      442        70.3   male        18 non-carrier         71.3
    ## 443      443        64.9   male        20     carrier            .
    ## 444      444        67.6 female        16 non-carrier            .
    ## 445      445        65.6 female        16 non-carrier            .
    ## 446      446        56.0   male        16     carrier            .
    ## 447      447        60.9   male        16 non-carrier            .
    ## 448      448        63.7   male        12     carrier         68.5
    ## 449      449        65.7   male        16     carrier         69.6
    ## 450      450        58.0 female        16 non-carrier            .
    ## 451      451        67.9 female        16 non-carrier            .
    ## 452      452        63.2   male        16     carrier         70.1
    ## 453      453        62.7   male        18 non-carrier         68.6
    ## 454      454        60.3 female        16     carrier            .
    ## 455      455        60.6 female        18 non-carrier            .
    ## 456      456        65.2   male        16 non-carrier            .
    ## 457      457        66.5 female        12     carrier            .
    ## 458      458        58.7   male        16     carrier            .
    ## 459      459        62.0   male        16 non-carrier            .
    ## 460      460        66.6 female        16 non-carrier            .
    ## 461      461        63.6   male        18 non-carrier            .
    ## 462      462        71.5   male        16 non-carrier            .
    ## 463      463        68.7 female        16     carrier            .
    ## 464      464        66.8   male        20 non-carrier            .
    ## 465      465        65.0   male        16 non-carrier            .
    ## 466      466        65.8   male        18 non-carrier            .
    ## 467      467        62.9   male        18 non-carrier            .
    ## 468      468        66.9 female        16     carrier            .
    ## 469      469        69.4 female        18 non-carrier            .
    ## 470      470        68.3   male        12 non-carrier            .
    ## 471      471        62.6   male        16     carrier         68.9
    ## 472      472        60.1 female        12 non-carrier            .
    ## 473      473        64.7 female        16 non-carrier            .
    ## 474      474        66.3   male        16 non-carrier            .
    ## 475      475        69.1   male        16 non-carrier            .
    ## 476      476        61.0   male        16 non-carrier            .
    ## 477      477        66.1 female        18 non-carrier            .
    ## 478      478        65.7   male        16 non-carrier            .
    ## 479      479        68.6 female        18 non-carrier            .
    ## 480      480        64.9 female        20 non-carrier            .
    ## 481      481        63.9   male        16 non-carrier            .
    ## 482      482        61.6   male        18 non-carrier            .
    ## 483      483        63.4   male        16     carrier            .

``` r
# delete no MCI at baseline
baseline$age_at_onset <- 
  replace(baseline$age_at_onset, baseline$age_at_onset == ".", NA)
cleaned_baseline <- 
  print(baseline) |>
  drop_na() 
```

    ##     study_id current_age sex education apoe4 age_at_onset
    ## 1          1        63.1   0        16     1         <NA>
    ## 2          2        65.6   0        20     1         <NA>
    ## 3          3        62.5   1        16     1         66.8
    ## 4          4        69.8   0        16     0         <NA>
    ## 5          5        66.0   1        16     0         68.7
    ## 6          6        62.5   1        16     0         <NA>
    ## 7          7        66.5   1        18     0           74
    ## 8          8        67.2   0        18     0         <NA>
    ## 9          9        66.7   0        16     0         <NA>
    ## 10        10        64.1   0        18     0         <NA>
    ## 11        11        69.5   0        16     0         <NA>
    ## 12        12        66.2   0        18     0         <NA>
    ## 13        13        63.1   1        12     1           69
    ## 14        14        58.4   0        20     0         66.2
    ## 15        15        68.4   1        20     0         <NA>
    ## 16        16        64.9   0        16     0         <NA>
    ## 17        17        65.0   0        18     0         <NA>
    ## 18        18        67.8   1        16     0         69.8
    ## 19        19        67.5   1        16     1         <NA>
    ## 20        20        66.8   1        16     0         <NA>
    ## 21        21        67.8   1        16     0         <NA>
    ## 22        22        67.3   0        20     1         74.6
    ## 23        23        65.2   1        18     0         <NA>
    ## 24        24        59.0   0        12     0         <NA>
    ## 25        25        66.9   1        16     0         <NA>
    ## 26        26        64.8   0        20     1         71.1
    ## 27        27        64.5   0        16     0         <NA>
    ## 28        28        60.6   1        20     0         <NA>
    ## 29        29        63.6   1        16     0         <NA>
    ## 30        30        66.3   0        12     0         73.1
    ## 31        31        69.1   0        12     0         <NA>
    ## 32        32        64.7   1        16     0         <NA>
    ## 33        33        66.2   1        18     0         <NA>
    ## 34        34        64.8   0        16     1         <NA>
    ## 35        35        60.9   0        12     0         <NA>
    ## 36        36        63.8   1        16     0         <NA>
    ## 37        37        63.8   1        16     0         <NA>
    ## 38        38        64.8   0        18     0         <NA>
    ## 39        39        68.3   0        16     1         70.2
    ## 40        40        67.3   1        16     0         <NA>
    ## 41        41        64.5   1        16     0         <NA>
    ## 42        42        64.2   1        16     0         <NA>
    ## 43        43        67.1   0        16     1         71.6
    ## 44        44        66.7   1        20     0         <NA>
    ## 45        45        62.9   1        20     1         65.2
    ## 46        46        62.9   1        16     0         <NA>
    ## 47        47        66.1   0        12     1         <NA>
    ## 48        48        67.3   1        16     0         <NA>
    ## 49        49        64.7   1        16     0         68.4
    ## 50        50        67.6   0        18     1         <NA>
    ## 51        51        66.2   1        16     0         <NA>
    ## 52        52        63.2   0        16     1         <NA>
    ## 53        53        66.0   1        20     0         <NA>
    ## 54        54        61.6   0        16     0         <NA>
    ## 55        55        69.3   0        16     1         73.6
    ## 56        56        70.9   1        20     0         <NA>
    ## 57        57        63.9   0        16     0         <NA>
    ## 58        58        61.9   1        12     0         <NA>
    ## 59        59        66.7   0        20     1         74.4
    ## 60        60        64.6   1        18     0         <NA>
    ## 61        61        72.2   1        16     0         <NA>
    ## 62        62        64.9   0        18     0         <NA>
    ## 63        63        67.1   0        20     0         <NA>
    ## 64        64        65.1   1        16     1         <NA>
    ## 65        65        62.8   0        16     0         66.5
    ## 66        66        65.6   0        20     0         <NA>
    ## 67        67        59.6   1        18     0         64.2
    ## 68        68        69.4   1        20     0         <NA>
    ## 69        69        65.5   0        20     1         72.5
    ## 70        70        71.5   1        16     0         <NA>
    ## 71        71        66.4   1        16     0         <NA>
    ## 72        72        62.9   1        16     1         62.5
    ## 73        73        66.8   0        18     0         <NA>
    ## 74        74        62.2   1        20     1         <NA>
    ## 75        75        61.2   0        16     1         65.4
    ## 76        76        65.9   1        12     0           68
    ## 77        77        63.7   0        18     1         66.4
    ## 78        78        65.0   1        16     0           68
    ## 79        79        65.2   1        16     0         <NA>
    ## 80        80        63.2   1        20     0         <NA>
    ## 81        81        63.3   1        16     0         <NA>
    ## 82        82        64.6   1        12     0         <NA>
    ## 83        83        68.5   0        12     0         <NA>
    ## 84        84        60.4   1        20     0         <NA>
    ## 85        85        66.8   0        16     0         <NA>
    ## 86        86        66.0   0        18     1         71.7
    ## 87        87        68.2   1        18     0           76
    ## 88        88        64.1   1        16     0         <NA>
    ## 89        89        66.1   0        16     1         66.2
    ## 90        90        65.8   1        16     0         <NA>
    ## 91        91        63.4   1        16     1         <NA>
    ## 92        92        68.6   0        20     0         <NA>
    ## 93        93        68.5   1        16     1         <NA>
    ## 94        94        67.1   1        16     0         <NA>
    ## 95        95        69.8   0        16     0         <NA>
    ## 96        96        66.7   0        16     0         <NA>
    ## 97        97        61.2   1        16     0         <NA>
    ## 98        98        63.3   0        16     1         <NA>
    ## 99        99        61.3   0        20     0         <NA>
    ## 100      100        63.6   0        16     0         <NA>
    ## 101      101        63.1   0        16     0         <NA>
    ## 102      102        65.1   1        16     0         <NA>
    ## 103      103        62.3   1        16     0         <NA>
    ## 104      104        65.5   1        12     0         <NA>
    ## 105      105        63.0   1        20     0         <NA>
    ## 106      106        70.3   0        16     1         74.8
    ## 107      107        67.2   1        16     1         <NA>
    ## 108      108        67.7   1        16     0         <NA>
    ## 109      109        66.2   0        16     1         68.4
    ## 110      110        70.0   1        16     0         <NA>
    ## 111      111        63.1   1        16     0         <NA>
    ## 112      112        63.6   0        18     0         <NA>
    ## 113      113        69.3   1        16     1         <NA>
    ## 114      114        63.0   0        18     1         <NA>
    ## 115      115        64.4   0        20     0         <NA>
    ## 116      116        63.8   1        20     0         <NA>
    ## 117      117        64.0   1        18     1         <NA>
    ## 118      118        64.2   0        16     1         <NA>
    ## 119      119        66.5   1        16     0         <NA>
    ## 120      120        64.5   0        20     1         72.2
    ## 121      121        63.5   1        18     0         <NA>
    ## 122      122        69.0   0        16     0         <NA>
    ## 123      123        64.4   1        18     1         67.4
    ## 124      124        64.5   0        16     0         <NA>
    ## 125      125        64.7   0        18     1         <NA>
    ## 126      126        67.1   0        20     0         <NA>
    ## 127      127        64.8   1        16     0         <NA>
    ## 128      128        64.9   1        12     0         <NA>
    ## 129      129        63.0   1        16     0         <NA>
    ## 130      130        64.0   1        18     1         <NA>
    ## 131      131        65.2   0        12     0         <NA>
    ## 132      132        63.2   1        16     1           66
    ## 133      133        66.6   1        18     0         <NA>
    ## 134      134        60.4   1        16     1         <NA>
    ## 135      135        65.9   1        16     0         <NA>
    ## 136      136        60.4   1        16     0         <NA>
    ## 137      137        64.1   1        16     0         <NA>
    ## 138      138        63.4   0        16     1         <NA>
    ## 139      139        63.0   0        18     0         <NA>
    ## 140      140        64.8   1        16     0         <NA>
    ## 141      141        59.3   1        16     1         <NA>
    ## 142      142        68.5   1        18     0         <NA>
    ## 143      143        60.0   0        20     0         <NA>
    ## 144      144        63.6   1        16     0         <NA>
    ## 145      145        61.7   0        18     0         <NA>
    ## 146      146        62.7   0        16     0         66.7
    ## 147      147        71.3   1        16     0         <NA>
    ## 148      148        65.1   1        16     0         <NA>
    ## 149      149        61.1   0        16     1         68.9
    ## 150      150        60.1   1        12     0         <NA>
    ## 151      151        66.4   0        16     0         <NA>
    ## 152      152        64.9   1        16     0         <NA>
    ## 153      153        64.0   0        16     0         <NA>
    ## 154      154        62.2   0        16     0         <NA>
    ## 155      155        60.5   0        12     0         <NA>
    ## 156      156        61.8   1        18     0         <NA>
    ## 157      157        68.0   1        16     1         <NA>
    ## 158      158        63.1   1        18     0         <NA>
    ## 159      159        60.8   1        16     0         <NA>
    ## 160      160        70.6   1        16     0         <NA>
    ## 161      161        66.3   1        16     1         <NA>
    ## 162      162        64.3   1        16     1         <NA>
    ## 163      163        68.2   0        12     0         <NA>
    ## 164      164        67.7   1        16     0         <NA>
    ## 165      165        63.1   0        20     0         <NA>
    ## 166      166        71.6   1        12     1         74.2
    ## 167      167        64.2   0        16     0         <NA>
    ## 168      168        60.7   1        16     0         <NA>
    ## 169      169        64.6   0        16     0         <NA>
    ## 170      170        65.6   1        16     0         70.7
    ## 171      171        71.9   0        20     0         <NA>
    ## 172      172        65.3   0        20     0         <NA>
    ## 173      173        66.4   1        12     1         <NA>
    ## 174      174        64.8   1        16     0         <NA>
    ## 175      175        64.0   0        18     0         <NA>
    ## 176      176        64.9   1        18     0         <NA>
    ## 177      177        67.4   0        16     1         74.4
    ## 178      178        71.2   0        20     0         <NA>
    ## 179      179        68.1   1        16     0         <NA>
    ## 180      180        68.6   1        16     0         <NA>
    ## 181      181        61.3   1        12     1         <NA>
    ## 182      182        68.0   1        18     1         <NA>
    ## 183      183        65.7   1        16     1         <NA>
    ## 184      184        60.6   1        20     0         <NA>
    ## 185      185        66.6   0        12     0         <NA>
    ## 186      186        64.5   1        20     1         69.5
    ## 187      187        69.4   1        16     0         <NA>
    ## 188      188        62.7   0        12     0         <NA>
    ## 189      189        63.7   1        16     0         <NA>
    ## 190      190        62.2   1        12     0         <NA>
    ## 191      191        64.5   0        16     0         <NA>
    ## 192      192        66.2   0        16     1         <NA>
    ## 193      193        62.8   1        20     1         <NA>
    ## 194      194        67.5   0        16     1         <NA>
    ## 195      195        61.4   1        18     1         <NA>
    ## 196      196        61.9   0        16     0         <NA>
    ## 197      197        69.3   0        16     0         <NA>
    ## 198      198        62.0   0        18     0         <NA>
    ## 199      199        66.2   1        18     0         <NA>
    ## 200      200        63.9   1        16     0         <NA>
    ## 201      201        66.2   1        18     0         <NA>
    ## 202      202        70.1   0        18     1         75.2
    ## 203      203        69.8   0        18     0         <NA>
    ## 204      204        64.0   0        16     0         <NA>
    ## 205      205        58.1   0        16     1         <NA>
    ## 206      206        72.5   0        16     0         <NA>
    ## 207      207        67.0   0        16     0         <NA>
    ## 208      208        66.6   0        18     0         <NA>
    ## 209      209        65.0   1        16     0         <NA>
    ## 210      210        66.5   0        16     0         <NA>
    ## 211      211        64.5   1        16     0         <NA>
    ## 212      212        66.3   0        16     1         <NA>
    ## 213      213        63.8   1        16     0         <NA>
    ## 214      214        60.9   1        16     0         <NA>
    ## 215      215        68.0   1        16     0         <NA>
    ## 216      216        69.6   0        12     0         <NA>
    ## 217      217        64.1   0        16     0         <NA>
    ## 218      218        61.2   1        16     0         65.9
    ## 219      219        66.9   0        16     1         <NA>
    ## 220      220        64.9   1        16     0         <NA>
    ## 221      221        59.8   0        18     0         <NA>
    ## 222      222        65.0   1        16     0         <NA>
    ## 223      223        63.1   0        20     1         <NA>
    ## 224      224        64.0   0        12     0         <NA>
    ## 225      225        61.5   1        16     0         <NA>
    ## 226      226        70.4   1        16     0         75.4
    ## 227      227        64.0   1        16     1         <NA>
    ## 228      228        60.2   1        12     0         <NA>
    ## 229      229        65.6   0        18     0         70.9
    ## 230      230        65.8   0        20     1         70.8
    ## 231      231        62.0   1        12     1         <NA>
    ## 232      232        56.3   1        16     0         <NA>
    ## 233      233        63.1   1        16     0         <NA>
    ## 234      234        66.7   1        18     0         66.7
    ## 235      235        64.8   1        16     0         <NA>
    ## 236      236        64.7   0        18     0         <NA>
    ## 237      237        66.7   1        16     0         <NA>
    ## 238      238        61.4   1        16     0         <NA>
    ## 239      239        68.3   1        16     0         <NA>
    ## 240      240        65.0   0        16     1         <NA>
    ## 241      241        67.1   1        12     0         <NA>
    ## 242      242        68.1   1        12     0         75.6
    ## 243      243        65.7   1        18     0         <NA>
    ## 244      244        62.4   1        16     0         <NA>
    ## 245      245        68.5   0        16     0         <NA>
    ## 246      246        59.0   0        16     0         <NA>
    ## 247      247        63.4   0        16     0         <NA>
    ## 248      248        64.2   0        20     0         <NA>
    ## 249      249        64.5   0        16     1         68.4
    ## 250      250        68.1   1        16     1         74.5
    ## 251      251        65.4   1        16     0         <NA>
    ## 252      252        66.2   1        16     1         69.6
    ## 253      253        64.8   0        16     0         <NA>
    ## 254      254        64.3   0        16     0         <NA>
    ## 255      255        67.1   1        20     0         <NA>
    ## 256      256        68.4   1        16     0         <NA>
    ## 257      257        57.8   1        18     0         <NA>
    ## 258      258        66.7   1        16     0         <NA>
    ## 259      259        66.1   0        16     0         <NA>
    ## 260      260        63.7   1        18     1         <NA>
    ## 261      261        67.9   1        16     1         <NA>
    ## 262      262        63.8   0        16     0         <NA>
    ## 263      263        64.1   1        18     0         <NA>
    ## 264      264        67.6   0        16     0         <NA>
    ## 265      265        70.2   1        16     0         <NA>
    ## 266      266        65.8   1        16     0         <NA>
    ## 267      267        63.7   1        16     0         <NA>
    ## 268      268        61.4   0        18     1         67.5
    ## 269      269        64.0   1        20     0         <NA>
    ## 270      270        62.2   1        16     1         <NA>
    ## 271      271        64.2   1        12     1         <NA>
    ## 272      272        66.2   1        16     1         <NA>
    ## 273      273        62.4   0        16     0         <NA>
    ## 274      274        72.9   0        16     0         <NA>
    ## 275      275        65.5   0        12     0         <NA>
    ## 276      276        68.4   0        16     1         <NA>
    ## 277      277        58.1   1        16     1         61.6
    ## 278      278        67.2   0        16     0         <NA>
    ## 279      279        61.1   0        18     0         <NA>
    ## 280      280        67.8   0        16     1         71.8
    ## 281      281        66.2   1        16     1         <NA>
    ## 282      282        63.8   0        16     1         <NA>
    ## 283      283        69.0   1        16     0         68.3
    ## 284      284        62.9   0        16     0         <NA>
    ## 285      285        63.3   0        12     0         <NA>
    ## 286      286        62.0   1        16     1         67.4
    ## 287      287        63.0   1        16     1           68
    ## 288      288        67.8   0        16     0         <NA>
    ## 289      289        66.3   1        18     1         74.1
    ## 290      290        68.0   1        12     0         <NA>
    ## 291      291        63.8   1        16     0         <NA>
    ## 292      292        66.1   0        18     0         70.2
    ## 293      293        65.7   0        16     0         <NA>
    ## 294      294        60.7   1        18     0         <NA>
    ## 295      295        70.3   1        20     0         <NA>
    ## 296      296        65.4   0        16     0         <NA>
    ## 297      297        67.3   1        16     1         73.9
    ## 298      298        67.9   1        16     0         <NA>
    ## 299      299        64.8   1        16     0         <NA>
    ## 300      300        64.1   1        16     1         <NA>
    ## 301      301        67.7   0        16     0         73.4
    ## 302      302        61.9   1        16     1         <NA>
    ## 303      303        70.9   1        16     0         <NA>
    ## 304      304        63.8   0        16     0         <NA>
    ## 305      305        70.0   0        18     1         77.2
    ## 306      306        69.5   0        16     0         72.6
    ## 307      307        65.2   1        16     0         <NA>
    ## 308      308        66.7   0        12     1         <NA>
    ## 309      309        61.9   0        18     0         <NA>
    ## 310      310        66.0   1        16     1         <NA>
    ## 311      311        68.1   1        16     0         <NA>
    ## 312      312        65.3   1        16     0         <NA>
    ## 313      313        63.6   1        18     0         <NA>
    ## 314      314        63.0   0        16     0         68.7
    ## 315      315        64.9   0        16     0         <NA>
    ## 316      316        68.2   0        16     0         <NA>
    ## 317      317        63.5   1        18     0         <NA>
    ## 318      318        64.6   1        12     0         <NA>
    ## 319      319        61.1   0        16     0         <NA>
    ## 320      320        66.5   1        18     0         <NA>
    ## 321      321        68.9   0        16     0         <NA>
    ## 322      322        69.5   1        20     1         <NA>
    ## 323      323        67.4   0        16     1         73.9
    ## 324      324        59.4   1        16     0         <NA>
    ## 325      325        66.4   1        16     0         <NA>
    ## 326      326        66.4   0        16     0         <NA>
    ## 327      327        63.9   1        16     0         <NA>
    ## 328      328        65.5   1        16     0           71
    ## 329      329        62.4   1        12     0         <NA>
    ## 330      330        67.0   0        18     1         <NA>
    ## 331      331        64.0   1        16     0         <NA>
    ## 332      332        60.3   0        12     0         <NA>
    ## 333      333        63.9   1        16     1         <NA>
    ## 334      334        69.1   1        20     0         <NA>
    ## 335      335        64.0   0        18     0         <NA>
    ## 336      336        67.2   0        16     1         73.7
    ## 337      337        67.8   0        16     0           75
    ## 338      338        65.0   0        16     0         70.8
    ## 339      339        63.9   0        12     0         <NA>
    ## 340      340        63.4   1        16     0         <NA>
    ## 341      341        67.2   1        18     0         <NA>
    ## 342      342        61.8   1        20     0         <NA>
    ## 343      343        65.7   0        12     0         <NA>
    ## 344      344        64.1   1        12     1         <NA>
    ## 345      345        58.2   1        18     0         <NA>
    ## 346      346        60.8   1        16     1         <NA>
    ## 347      347        67.7   1        16     1         68.9
    ## 348      348        64.4   1        16     1         70.4
    ## 349      349        67.4   0        18     1           70
    ## 350      350        70.7   0        16     1         75.2
    ## 351      351        69.4   1        16     1         76.6
    ## 352      352        67.0   1        16     1         69.3
    ## 353      353        66.1   1        16     0         <NA>
    ## 354      354        64.4   1        20     1         <NA>
    ## 355      355        69.7   1        16     1         75.3
    ## 356      356        66.8   0        20     0         <NA>
    ## 357      357        61.5   0        20     0         <NA>
    ## 358      358        64.5   1        12     1         <NA>
    ## 359      359        59.2   1        18     0         <NA>
    ## 360      360        64.4   0        18     0         <NA>
    ## 361      361        57.2   0        18     1         <NA>
    ## 362      362        68.9   0        16     0         <NA>
    ## 363      363        63.1   1        20     0         <NA>
    ## 364      364        63.7   1        18     0         <NA>
    ## 365      365        64.5   0        16     0         67.7
    ## 366      366        66.8   1        16     1         72.8
    ## 367      367        67.0   0        16     0         <NA>
    ## 368      368        66.7   1        16     0         <NA>
    ## 369      369        63.3   1        18     1         68.6
    ## 370      370        60.9   0        16     1         <NA>
    ## 371      371        63.8   1        12     1         <NA>
    ## 372      372        65.8   1        16     0         <NA>
    ## 373      373        62.5   1        16     0           66
    ## 374      374        64.8   1        18     0         <NA>
    ## 375      375        61.5   0        16     0         <NA>
    ## 376      376        65.0   0        16     0         <NA>
    ## 377      377        65.4   0        16     1         68.2
    ## 378      378        64.6   0        16     1         <NA>
    ## 379      379        64.5   1        16     0         70.9
    ## 380      380        70.3   0        16     0         70.2
    ## 381      381        67.3   0        16     1         <NA>
    ## 382      382        68.3   0        20     0         <NA>
    ## 383      383        62.2   1        18     0         <NA>
    ## 384      384        65.5   1        16     0         <NA>
    ## 385      385        68.5   1        20     0         <NA>
    ## 386      386        64.8   1        16     1         <NA>
    ## 387      387        58.6   1        16     1         <NA>
    ## 388      388        66.0   0        16     0         <NA>
    ## 389      389        59.3   0        16     0         <NA>
    ## 390      390        62.6   0        16     0         <NA>
    ## 391      391        69.0   0        18     0         <NA>
    ## 392      392        66.8   1        16     0         <NA>
    ## 393      393        68.3   1        12     0         <NA>
    ## 394      394        65.9   0        16     0         <NA>
    ## 395      395        64.7   0        12     0         <NA>
    ## 396      396        62.2   1        18     0         <NA>
    ## 397      397        69.8   0        16     0         <NA>
    ## 398      398        65.1   0        16     0           73
    ## 399      399        62.9   1        18     0         <NA>
    ## 400      400        67.6   0        16     0         71.9
    ## 401      401        68.2   1        20     0         <NA>
    ## 402      402        70.7   0        16     0         <NA>
    ## 403      403        63.2   0        16     1         <NA>
    ## 404      404        63.8   1        20     1         <NA>
    ## 405      405        63.8   1        18     0         <NA>
    ## 406      406        63.9   0        16     0         <NA>
    ## 407      407        63.9   1        16     0         <NA>
    ## 408      408        64.1   1        20     1         70.2
    ## 409      409        69.3   1        16     1         75.2
    ## 410      410        62.9   1        16     0         <NA>
    ## 411      411        63.8   1        16     1         <NA>
    ## 412      412        67.0   1        16     1         <NA>
    ## 413      413        68.4   1        20     0         <NA>
    ## 414      414        62.7   0        16     0         <NA>
    ## 415      415        63.5   1        18     0         <NA>
    ## 416      416        66.6   0        16     0         68.9
    ## 417      417        68.1   0        16     1         72.5
    ## 418      418        64.2   1        12     1         <NA>
    ## 419      419        60.7   0        16     1         63.8
    ## 420      420        70.1   1        16     0         <NA>
    ## 421      421        69.3   0        16     0         <NA>
    ## 422      422        62.9   0        12     1         <NA>
    ## 423      423        64.8   0        16     1         70.3
    ## 424      424        59.7   1        18     1         62.9
    ## 425      425        66.7   1        16     0         <NA>
    ## 426      426        69.8   1        16     0         76.8
    ## 427      427        60.1   1        12     0         <NA>
    ## 428      428        62.7   1        18     0         <NA>
    ## 429      429        63.1   1        16     1         <NA>
    ## 430      430        63.0   0        20     0         <NA>
    ## 431      431        58.9   1        16     1         61.2
    ## 432      432        66.5   0        16     0         <NA>
    ## 433      433        60.4   1        12     1         <NA>
    ## 434      434        64.9   1        16     0         <NA>
    ## 435      435        66.8   0        16     0         <NA>
    ## 436      436        64.4   1        12     1         <NA>
    ## 437      437        67.7   0        18     1         <NA>
    ## 438      438        64.9   0        16     0         <NA>
    ## 439      439        63.1   0        16     0         <NA>
    ## 440      440        66.9   1        16     1         72.3
    ## 441      441        63.7   0        18     0         <NA>
    ## 442      442        70.3   1        18     0         71.3
    ## 443      443        64.9   1        20     1         <NA>
    ## 444      444        67.6   0        16     0         <NA>
    ## 445      445        65.6   0        16     0         <NA>
    ## 446      446        56.0   1        16     1         <NA>
    ## 447      447        60.9   1        16     0         <NA>
    ## 448      448        63.7   1        12     1         68.5
    ## 449      449        65.7   1        16     1         69.6
    ## 450      450        58.0   0        16     0         <NA>
    ## 451      451        67.9   0        16     0         <NA>
    ## 452      452        63.2   1        16     1         70.1
    ## 453      453        62.7   1        18     0         68.6
    ## 454      454        60.3   0        16     1         <NA>
    ## 455      455        60.6   0        18     0         <NA>
    ## 456      456        65.2   1        16     0         <NA>
    ## 457      457        66.5   0        12     1         <NA>
    ## 458      458        58.7   1        16     1         <NA>
    ## 459      459        62.0   1        16     0         <NA>
    ## 460      460        66.6   0        16     0         <NA>
    ## 461      461        63.6   1        18     0         <NA>
    ## 462      462        71.5   1        16     0         <NA>
    ## 463      463        68.7   0        16     1         <NA>
    ## 464      464        66.8   1        20     0         <NA>
    ## 465      465        65.0   1        16     0         <NA>
    ## 466      466        65.8   1        18     0         <NA>
    ## 467      467        62.9   1        18     0         <NA>
    ## 468      468        66.9   0        16     1         <NA>
    ## 469      469        69.4   0        18     0         <NA>
    ## 470      470        68.3   1        12     0         <NA>
    ## 471      471        62.6   1        16     1         68.9
    ## 472      472        60.1   0        12     0         <NA>
    ## 473      473        64.7   0        16     0         <NA>
    ## 474      474        66.3   1        16     0         <NA>
    ## 475      475        69.1   1        16     0         <NA>
    ## 476      476        61.0   1        16     0         <NA>
    ## 477      477        66.1   0        18     0         <NA>
    ## 478      478        65.7   1        16     0         <NA>
    ## 479      479        68.6   0        18     0         <NA>
    ## 480      480        64.9   0        20     0         <NA>
    ## 481      481        63.9   1        16     0         <NA>
    ## 482      482        61.6   1        18     0         <NA>
    ## 483      483        63.4   1        16     1         <NA>

``` r
cleaned_baseline$age_at_onset <- as.numeric(cleaned_baseline$age_at_onset)
```

After importing and reformatting the dataset, the “sex” and “APOE4”
variables were converted to meaningful characters, and participants who
did not develop MCI were removed from the dataset. At the beginning,
this study recruited 483 participants, and among them only 97
participants develop MCI. Based on the data from cleaned version, the
average baseline age is around 70.2628866 years, and based on the total
participants, the proportion of women are carriers is around NaN%
people.

``` r
# Read CSV files:
amyloid <- 
  read.csv("data_mci/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  drop_na()
# convert to long format
amyloid_long <- amyloid %>%
  pivot_longer(baseline:time_8, 
               names_to = "time", 
               values_to = "value")
```

After importing and reformatting the dataset, all “NA” values were
deleted, and the dataset was convert into long format. There are 0
participants appear in only the baseline dataset, and 347 participants
appear in only the amyloid dataset.

``` r
# Merge datasets
combined_mci <- merge(baseline, amyloid_long, by = "study_id" )
# Exporting the combined_mci to a CSV file
write.csv(combined_data, "data_mci/combined_dataset.csv", row.names = FALSE)
```

The “combined_mci” dataset is a combination of data derived from
baseline and amyloid_long. This combination includes both demographic
details and observed biomarker values, easier to analysis Alzheimer’s
disease.
